### ISSUE TITLE
Decide what operations users might do

### ISSUE THREAD

**Issue by alex-j6** [Aidenjn/Personal-Data-Visualization-Tool#21]
- enter folder path which includes all json files

**Comment by Aidenjn** [comment]
Here is what I think the CLI functionality may look like:
> python3 pd-analyzer [path to folder downloaded from facebook]

Please choose a visualization:
1. What are my top 10 most used words?
2. Who have I poked the most?
3. Who are the friends I interact with the most?
4. Question
5. Another question
6. etc…

> [enter input]

Visualization produced at [path to generated visualization]
